import os
import sys

sys.path.append("./workflow/scripts/snakemake_helpers")

from snakemake_helpers import *

#----- Snakemake Set Up -----#

configfile: "./config/demux_config.yaml"

#----- Rename input files -----#

rename_files(config)

READDIR = config["Paths"]["Reads"]
READEXT = config["Patterns"]["ReadExtensions"]

SAMPLES, = glob_wildcards(os.path.join(READDIR, "{sample}_R1.fastq.gz")) 
SEQTYPE = ["R1", "R2", "I1", "I2"]

PATTERN_R1 = "{sample}_R1"
PATTERN_R2 = "{sample}_R2"
PATTERN_I1 = "{sample}_I1"
PATTERN_I2 = "{sample}_I2"

#----- Snakemake Workflow -----#

rule concatenate:
	input:
		expand("READDIR/{sample}_{seqType}{readExt}", sample = SAMPLES, seqType = SEQTYPE, readExt = READEXT)
	output:
		expand("READDIR/concatenated/{seqType}.fastq.gz", seqType = SEQTYPE)
	shell:
		"cat input > output"
